
[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[general]
import = ["/home/orbis/.config/alacritty/oxocarbon.toml"]

[cursor.style]
blinking = "On"

[window]
opacity = 0.8
