
[font]
size = 13.0

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[general]
import = ["/home/benjamin/.config/alacritty/teide_darker.toml"]

[cursor.style]
blinking = "On"

[window]
opacity = 1
